Refactor, Remove Java deps and introduce nf-schema
Ensembl/ensembl-genes-nf pull request #12
Opened 2024-11-22 10:14 UTC by ens-LCampbell

Hi @ens-ftricomi here is my PR for the BUSCO pipeline changes required to ease its use across wider teams and remove some groovy/java deps and facilitate bumping to a more recent nextflow version. 

In summary the main changes are as follows:
- Remove use of java mysql code
- Increase nextflow version getting away from v22.10 which lacks proper resource management in SLURM. 
- Introduce [nf-schema 2.0](https://nextflow-io.github.io/nf-schema/latest/) and pipeline param runtime validation.
- Add samplesheetToList and CSV file validation. 
- A new database meta table module to facilitate meta data propagation and flow through. The module _perpare_metadata_ is fiarly standalone and relies on ensembl-genomio python code accessed via a its [docker container].(https://hub.docker.com/r/ensemblorg/ensembl-genomio/tags). 
- Refinements to some modules (removal of redundancy where possible) and my attempt to adhere to the slowly developing [Ensembl Nextflow coding guidelines](https://www.ebi.ac.uk/seqdb/confluence/display/EnsGen/Nextflow+coding+guidelines). 

Given the large scope of this PR, I would be happy to discuss over a huddle or call at some point. I suggest the first thing to do is to run it on an example DB or example CSV. I have done my best to not change the actual pipeline itself in terms of how and what it originally produced and I have tested this to ensure its not changed anything drastically. I've asked Plantazoa members to test it more on our end for more feedback and will relay/update if needed. 

Could you consider which branch is best to merge the PR once happy. I don't want to overwrite an old branch so perhaps a new branch entirely. 

Best, Lahcen

2025-02-11 19:01 UTC, JAlvarezJarreta requested changes
Just mainly minor documentation typos or removal of commented/unnecessary code, looks good otherwise.

I believe `mysql-connector-j-8.0.31.jar` can be dropped as well since it is no longer necessary.

2025-02-11 19:01 UTC, JAlvarezJarreta commented on NOTICE
> +Copyright 2020-2022 EMBL-European Bioinformatics Institute
```suggestion
Copyright 2020-2025 EMBL-European Bioinformatics Institute
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/conf/busco.config
> +        busco_version = 'v5.7.1_cv1' // metaeuk 'v5.4.7_cv1'
```suggestion
        busco_version = 'v5.7.1_cv1'
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/conf/busco.config
> +        //path for supplementary scripts
```suggestion
        // Path for supplementary scripts
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/conf/genomio.config
> +        genomio_version = 'GenomioDockerRebuild_v1.5.0a' // container with 'ps' added, an nxf requirement
```suggestion
        genomio_version = 'v1.6.0'
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/conf/omark.config
> +
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/busco/busco_core_metakeys.nf
> +#!/usr/bin/env nextflow
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/busco/busco_core_metakeys.nf
> +    // afterScript "sleep $params.files_latency" // Needed because of file system latency
Either it is needed or not needed at all:
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/busco/busco_core_metakeys.nf
> +            val(publish_dir_name), path(summary_file)
```suggestion
        tuple val(insdc_acc), val(dbname), val(formatted_sci_name), val(publish_dir_name), path(summary_file)
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/busco/busco_dataset.nf
> +#!/usr/bin/env nextflow
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/busco/busco_dataset.nf
> +    // storeDir "${params.cacheDir}/${dbname}/meta_data/"
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on README.md
> +If only the assembly accession and the taxon id are available the pipeline provide Busco score (mode=genome) for the assembly.
```suggestion
If only the assembly accession and the taxon id are available the pipeline provides Busco score (mode=genome) for the assembly.
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on README.md
> +Option available to check the quality of the genome (accession dependent,core database independent) by running Busco in genome mode.
```suggestion
Option available to check the quality of the genome (accession dependent, core database independent) by running Busco in genome mode.
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/busco/busco_core_metakeys.nf
> +
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/busco/busco_lineages.nf
> +    // afterScript "sleep ${params.files_latency}"  // Needed because of file system latency
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/busco/busco_output.nf
> +#!/usr/bin/env nextflow
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/busco/busco_output.nf
> +        }
I doubt we want BRC (VEuPathDB) legacy code here:
```suggestion
        gca_string = insdc_acc.toLowerCase().replaceAll(/\./, "v").replaceAll(/_/, "")
        summary_name = [species_lc, gca_string, busco_sum, "short_summary.txt"].join("_")
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/copy_output_to_ensembl_ftp.nf
> +#!/usr/bin/env nextflow
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/copy_output_to_ensembl_ftp.nf
> +        // ftp_path = "${params.production_ftp_dir}/${formated_sci_name}"
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/copy_output_to_ensembl_ftp.nf
> +        //sudo -u genebuild rsync -ahvW $summary_file $ftp_stats && rsync -avhc $summary_file $ftp_stats;
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/ensembl_statistics/populate_db.nf
> +#!/usr/bin/env nextflow
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/ensembl_statistics/run_ensembl_meta.nf
> +#!/usr/bin/env nextflow
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/ensembl_statistics/run_ensembl_meta.nf
> +    // storeDir "${params.cacheDir}/$insdc_acc/"
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/ensembl_statistics/run_ensembl_meta.nf
> +
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/ensembl_statistics/run_ensembl_meta.nf
> +
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/ensembl_statistics/run_statistics.nf
> +#!/usr/bin/env nextflow
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/ensembl_statistics/run_statistics.nf
> +    afterScript "sleep ${params.files_latency}"  // Needed because of file system latency
Not sure why in some places this is commented and not in others, but will go with it.

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/fetch_genome.nf
> +#!/usr/bin/env nextflow
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/fetch_genome.nf
> +//ncbi_dataset/data/GCA_963576655.1/GCA_963576655.1_icGasPoly1.1_genomic.fna
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/fetch_proteins.nf
> +#!/usr/bin/env nextflow
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/omark/omamer_hog.nf
> +#!/usr/bin/env nextflow
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/omark/omark.nf
> +#!/usr/bin/env nextflow
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/omark/omark_output.nf
> +#!/usr/bin/env nextflow
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/utils.nf
> +*/
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/subworkflows/run_busco.nf
> +#!/usr/bin/env nextflow
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/subworkflows/run_busco.nf
> +        // // // Run Busco in genome mode
```suggestion
        // Run Busco in genome mode
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/subworkflows/run_busco.nf
> +        // // Run Busco in protein mode
```suggestion
        // Run Busco in protein mode
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/subworkflows/run_busco.nf
> +        // }
```suggestion

```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/subworkflows/run_ensembl_stats.nf
> +#!/usr/bin/env nextflow
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/subworkflows/run_omark.nf
> +#!/usr/bin/env nextflow
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/input_csv_schema.json
> +                    "errorMessage": "Please provide a valid INSDC accession.",
```suggestion
                    "errorMessage": "Please provide a valid INSDC accession",
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/nextflow.config
> +  // dbname  = null
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pyproject.toml
> +"setuptools"
```suggestion
keywords = [
    "ensembl", 
    "annotation", 
    "genetics",
    "bioinformatics",
    "setuptools"
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pyproject.toml
> +
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on requirements.txt
> +typing
Already part of Python standard libraries
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/bin/clade_selector.py
> +import json
```suggestion
import argparse
import json
from pathlib import Path
from typing import Any, List
import urllib.request
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/bin/clade_selector.py
> +            """
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/bin/clade_selector.py
> +    #print (matched_value)
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/bin/clade_selector.py
> +        #datasets = [line[: max(line.find(" "), 0) or None] for line in file]
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/bin/clade_selector.py
> +        #print(clade_match[0].strip("\n"))
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/bin/busco_metakeys_patch.py
> +from typing import Dict, Optional, Union
```suggestion

import argparse
import json
from pathlib import Path
import re
from typing import Dict, Optional, Union

import pymysql
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/bin/busco_metakeys_patch.py
> +    #data["core_db"] = db
```suggestion
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/bin/busco_metakeys_patch.py
> +            erroneus = score_match.group(7)
This code can be simplified:
```suggestion
    score_match = re.findall(r"(\d+\.\d+)", content)
    if score_match:
        score = score_match[0]
        total_buscos = score_match[6]
        if mode_match == "euk_genome_min":
            erroneus = score_match[7]
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/bin/busco_metakeys_patch.py
> +) -> str:  # pylint: disable=line-too-long
```suggestion
def generate_sql_patches(
        db_name: str,
        json_data: Dict[str, Union[str, float]],
        species_id: int = 1,
        table_name: str = "meta",
) -> str:
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/bin/busco_metakeys_patch.py
> +            f"INSERT IGNORE INTO {table_name} (species_id, meta_key, meta_value) VALUES ({species_id}, '{key}', '{value_str}');"  # pylint: disable=line-too-long
```suggestion
            f"INSERT IGNORE INTO {table_name} (species_id, meta_key, meta_value)"
            f"VALUES ({species_id}, '{key}', '{value_str}');"
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/bin/busco_metakeys_patch.py
> +) -> str:  # pylint: disable=line-too-long
```suggestion
) -> str:
```

2025-02-11 19:01 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/bin/busco_metakeys_patch.py
> +
```suggestion
```

2025-02-12 11:19 UTC, JAlvarezJarreta commented on pipelines/nextflow/subworkflows/run_busco.nf
> +            def output_typeG = "genome"
```suggestion
            output_typeG = "genome"
```
Use of groovy's `def` can cause unexpected behaviour.

2025-02-12 11:40 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/main.nf
> +            def copyToFtp = false
```suggestion
            busco_mode = 'genome'
            copyToFtp = false
```

2025-02-12 11:40 UTC, JAlvarezJarreta commented on pipelines/nextflow/workflows/main.nf
> +        // core_db_list.view()
```suggestion
```

2025-02-12 14:49 UTC, ens-LCampbell commented on pipelines/nextflow/modules/busco/busco_core_metakeys.nf
> +    // afterScript "sleep $params.files_latency" // Needed because of file system latency
Legacy stuff, perhaps needed so I will leave for now sorry

2025-02-12 15:02 UTC, ens-LCampbell commented on pipelines/nextflow/modules/ensembl_statistics/run_ensembl_meta.nf
> +    // storeDir "${params.cacheDir}/$insdc_acc/"
same, I do not want to remove this incase its needed.

2025-02-12 15:03 UTC, ens-LCampbell commented on pipelines/nextflow/modules/ensembl_statistics/run_statistics.nf
> +    afterScript "sleep ${params.files_latency}"  // Needed because of file system latency
If I once knew why I would comment, but i've since forgotten. I will leave as is for now

2025-02-12 16:25 UTC, JAlvarezJarreta approved these changes

2025-02-12 16:25 UTC, JAlvarezJarreta commented on pipelines/nextflow/conf/busco.config
> +        busco_version = 'v5.7.1_cv1'
Do we want to update it to `5.8`? I believe you have tested it and it is working better than its predecessors.

2025-02-12 16:26 UTC, ens-LCampbell commented on pipelines/nextflow/conf/busco.config
> +        busco_version = 'v5.7.1_cv1'
Already done, in between tasks right now but this will be applied yes.

2025-02-17 11:48 UTC, JAlvarezJarreta approved these changes
A couple of suggestions and one indentation issue, but looks good otherwise 👍

2025-02-17 11:48 UTC, JAlvarezJarreta commented on pipelines/nextflow/modules/busco/busco_output.nf
> +input:
```suggestion
    input:
```

2025-02-17 11:48 UTC, JAlvarezJarreta commented on pipelines/nextflow/subworkflows/run_busco.nf
> +            organism_name:row[4], annotation_source:row[5], ortho_db: row[6]]}
```suggestion
            .map { row -> [
                insdc_acc: row[0], taxonomy_id: row[1], core: row[2], production_name: row[3],
                organism_name: row[4], annotation_source: row[5], ortho_db: row[6]
            ]}
```
I find this a little bit more readable.

2025-02-17 11:48 UTC, JAlvarezJarreta commented on pipelines/nextflow/subworkflows/run_busco.nf
> +                organism_name:row[4], annotation_source:row[5], ortho_db: row[6], genome:row[7]]}
```suggestion
                .map { row -> [
                    insdc_acc: row[0], taxonomy_id: row[1], core: row[2], production_name: row[3],
                    organism_name: row[4], annotation_source: row[5], ortho_db: row[6], genome: row[7]
                ]}
```

2025-02-17 11:48 UTC, JAlvarezJarreta commented on pipelines/nextflow/subworkflows/run_busco.nf
> +                organism_name:row[4], annotation_source:row[5], report:row[6]]}
```suggestion
                .map { row -> [
                    insdc_acc: row[0], taxonomy_id: row[1], core: row[2],production_name: row[3],
                    organism_name: row[4], annotation_source: row[5], report: row[6]
                ]}
```

2025-02-17 11:48 UTC, JAlvarezJarreta commented on pipelines/nextflow/subworkflows/run_busco.nf
> +                organism_name:row[4], annotation_source:row[5], ortho_db: row[6], translations:row[7]]}
```suggestion
                .map { row -> [
                    insdc_acc: row[0], taxonomy_id: row[1], core: row[2], production_name: row[3],
                    organism_name: row[4], annotation_source: row[5], ortho_db: row[6], translations: row[7]
                ]}
```

2025-02-17 11:48 UTC, JAlvarezJarreta commented on pipelines/nextflow/subworkflows/run_busco.nf
> +                organism_name:row[4], annotation_source:row[5], report:row[6]]}
```suggestion
                .map { row -> [
                    insdc_acc: row[0], taxonomy_id: row[1], core: row[2], production_name: row[3],
                    organism_name: row[4], annotation_source: row[5], report: row[6]
                ]}
```

2025-03-18 10:45 UTC, closed without merging